# Generated by Django 5.2.6 on 2025-09-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
