# Generated by Django 5.2.6 on 2025-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_remove_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
