# Generated by Django 5.2.6 on 2025-09-19 10:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_investment_date_approved_withdrawal_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
